version: '3'

services:
  myapp:
   build: .
   ports:
    - 8080:8080
   restart: always
   depends_on:
    - db
    - mongo 
   environment:
    SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mediscreenPostGres
    SPRING_DATASOURCE_USERNAME: postgres
    SPRING_DATASOURCE_PASSWORD: ${DATABASE_PASSWORD}
    SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/mediscreenMongo
  db:
   image: postgres:12.19-alpine3.20
   ports:
    - 5432:5432
   environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    POSTGRES_DB: mediscreenPostGres
   volumes:
    - postgres_data:/var/lib/postgresql/data
  mongo:
    image: mongo:latest  
    volumes:
     - mongodb_data:/data/db
    ports:
     - 27017:27017 
volumes:
  postgres_data:
  mongodb_data:     